package com.odoohackathon.odoohackathon.domain.analytics.service;

import com.odoohackathon.odoohackathon.domain.analytics.dto.AnalyticsReportDTO;
import com.odoohackathon.odoohackathon.domain.trip.entity.Trip;
import com.odoohackathon.odoohackathon.domain.trip.repository.TripRepository;
import com.odoohackathon.odoohackathon.domain.user.entity.CompanyConfiguration;
import com.odoohackathon.odoohackathon.domain.user.entity.User;
import com.odoohackathon.odoohackathon.domain.user.repository.CompanyConfigurationRepository;
import com.odoohackathon.odoohackathon.domain.user.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.List;

@Service
@RequiredArgsConstructor
public class AnalyticsService {

    private final TripRepository tripRepository;
    private final UserRepository userRepository;
    private final CompanyConfigurationRepository configurationRepository;

    public AnalyticsReportDTO getCompanyDashboard(String adminEmail) {
        User admin = userRepository.findByEmail(adminEmail)
                .orElseThrow(() -> new IllegalArgumentException("Admin not found"));

        CompanyConfiguration config = configurationRepository.findByCompanyId(admin.getCompany().getId())
                .orElseGet(() -> CompanyConfiguration.builder()
                        .company(admin.getCompany())
                        .defaultFuelCostPerLiter(BigDecimal.valueOf(100.0)) // Default fallback
                        .defaultTravelCostPerKm(BigDecimal.valueOf(10.0))   // Default fallback
                        .build());

        // In a real scenario, you would filter trips by the admin's company.
        // For the hackathon scope, we fetch all trips or write a custom query.
        List<Trip> allTrips = tripRepository.findAll();

        long totalTrips = allTrips.size();
        
        // Mock distance calculation for hackathon: Assume avg trip is 15km
        double avgDistancePerTripKm = 15.0; 
        double totalDistance = totalTrips * avgDistancePerTripKm;

        // Mock fuel efficiency: Assume 15 km per liter
        double avgKmPerLiter = 15.0;
        double estimatedFuelLiters = totalDistance / avgKmPerLiter;

        // Calculate Cost Savings: Total Fare generated by carpooling vs standard cab fares
        BigDecimal totalFareExchanged = allTrips.stream()
                .map(Trip::getTotalFare)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        // Hypothetical standard cab cost is double the carpool fare
        BigDecimal hypotheticalCabCost = totalFareExchanged.multiply(BigDecimal.valueOf(2));
        BigDecimal totalCostSaved = hypotheticalCabCost.subtract(totalFareExchanged);

        BigDecimal costPerKm = BigDecimal.ZERO;
        if (totalDistance > 0) {
            costPerKm = totalFareExchanged.divide(BigDecimal.valueOf(totalDistance), 2, RoundingMode.HALF_UP);
        }

        return AnalyticsReportDTO.builder()
                .totalTrips(totalTrips)
                .totalDistanceTravelledKm(totalDistance)
                .estimatedFuelConsumptionLiters(estimatedFuelLiters)
                .totalCostSaved(totalCostSaved)
                .costPerKilometer(costPerKm)
                .build();
    }
}
