spring.application.name=Odoo-Hackathon

server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/carpooling_platform
spring.datasource.username=dev-trivedi
spring.datasource.password=password@123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

razorpay.key.id=rzp_test_TEtkcWeUnkc6xQ
razorpay.key.secret=7LAiBzIDrGZ4dIi7wqQ6YFPf

# JWT Configuration
jwt.secret=9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9
jwt.expiration=86400000

# ClickHouse Analytics Database
clickhouse.url=jdbc:clickhouse://localhost:8123/default
clickhouse.username=default
clickhouse.password=
